apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-loadbalancing
commonLabels:
  app: hello-kubernetes
  app.kubernetes.io/component: hello-kubernetes
  app.kubernetes.io/instance: hello-kubernetes
resources:
  - deploy.yml
  - service.yml
  - route.yml
